### ISSUE TITLE
MLSys: The New Frontier of Machine Learning Systems

### ISSUE THREAD

**Issue by dexhunter** [dyweb/papers-notebook#209]
https://arxiv.org/pdf/1904.03257.pdf

**Comment by dexhunter** [comment]
@gaocegege 感觉是个私人库，我都添加不了Label 😿

**Comment by dexhunter** [comment]
This paper is an overview of [the conference MLSys](https://mlsys.org/). The conference covers a range of topics including hardware systems for ML, software systems for ML and ML optimized for metrics beyond predictive accuracy. In my personal opinion, this conference attracts both academia and industry since companies such as Google, Microsoft are deploying MLaaS at a rapid speed.

A list of past papers could be found [here](https://proceedings.mlsys.org/book/2019)

**Comment by gaocegege** [comment]
需要权限。。
